In [1]:
import numpy as np

In [44]:
a = np.array([1,2,3], dtype='int32')
print(a)


[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int32')

In [15]:
a.itemsize

4

In [17]:
a.nbytes

12

In [20]:
a = np.array([[1, 2, 3, 4 ,5 , 6], [7, 8, 9 ,10, 11, 12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
a[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [22]:
a[1,3]

10

In [23]:
a[0,4]

5

In [24]:
a[:, 2]

array([3, 9])

In [26]:
a[0, 1:5]

array([2, 3, 4, 5])

In [27]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]


In [28]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6]
 [ 7  8  5 10 11 20]]


In [29]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [30]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [34]:
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [41]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [45]:
np.full_like(a, 4)

array([4, 4, 4])

In [46]:
np.random.rand(4,2)

array([[0.4847182 , 0.1490559 ],
       [0.15073608, 0.96511488],
       [0.79970156, 0.64823335],
       [0.60472774, 0.73276561]])

In [47]:
np.random.random_sample(a.shape)

array([0.30181456, 0.78058271, 0.43822947])

In [61]:
np.random.randint(4,7, size=(3,3))

array([[6, 5, 4],
       [6, 6, 5],
       [4, 4, 5]])

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [73]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [78]:
a = np.array([1,2,2,4])
print(a)

[1 2 2 4]


In [79]:
a + 2

array([3, 4, 4, 6])

In [80]:
a -2

array([-1,  0,  0,  2])

In [81]:
a * 2

array([2, 4, 4, 8])

In [82]:
a/2

array([0.5, 1. , 1. , 2. ])

In [83]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 3, 4])

In [84]:
a ** 2

array([ 1,  4,  4, 16], dtype=int32)

In [85]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.90929743, -0.7568025 ])

In [86]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.41614684, -0.65364362])

In [87]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [89]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [90]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.min(stats)

1

In [92]:
np.max(stats)

6

In [94]:
np.min(stats, axis=0)

array([1, 2, 3])

In [96]:
np.max(stats, axis=1)

array([3, 6])

In [97]:
np.sum(stats)

21

In [98]:
np.sum(stats, axis=1)

array([ 6, 15])

In [101]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [103]:
v1 =  np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h1, h2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.